### ISSUE TITLE
Errors During make

### ISSUE THREAD

**Issue by stooz5** [smithlabcode/preseq#69]
Hello,

I am trying to run a make and am getting errors regarding regex (errors attached).  Could you please review and let me know what could be the issue?

Thank you.
[preseq.txt](https://github.com/smithlabcode/preseq/files/13492664/preseq.txt)

**Comment by andrewdavidsmith** [comment]
Your specific compiler version has a bug for the regex library. Try anything more recent among gcc compilers.

**Comment by stooz5** [comment]
Thank you.  I loaded gcc 9.3.0 but now I am getting errors about GeniomicRegion and the make fails:

load_data_for_complexity.cpp:(.text+0x20b4): undefined reference to `GenomicRegion::assign_chrom(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
src/load_data_for_complexity.o:load_data_for_complexity.cpp:(.text+0x21f3): more undefined references to `GenomicRegion::assign_chrom(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' follow
src/load_data_for_complexity.o: In function `load_coverage_counts_MR(bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long, unsigned long, unsigned long, std::vector<double, std::allocator<double> >&)':

**Comment by stooz5** [comment]
Thank you.  I was able to compile using gcc 9.3.0.  However, when I try to run it, I get an error with glibcxx:

 preseq -h
preseq: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by preseq)
preseq: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by preseq)
preseq: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by preseq)

**Comment by andrewdavidsmith** [comment]
That's due to a mismatch in the environment likely caused by an incomplete installation or configuration of the new compiler. Are you administering your system? If so, I can probably give pointers. If not, you'd have to take it up with your admin.

**Comment by stooz5** [comment]
Yes, I am the admin.  We have an HPC cluster and I configured preseq as an R module which calls the binary.  We can normally configure binaries this way.

**Comment by andrewdavidsmith** [comment]
In that case I suggest fully removing all c compilers you are able to, and then reinstalling the one you are using (should be gcc 5.3 or later I think; I use 13 currently). This is the simplest
If you can do it. Otherwise we will need to adjust paths.

**Comment by stooz5** [comment]
thanks, I added module load gcc/9.3.0 in the R tcl file and it works fine now.  You can close this.

**Comment by andrewdavidsmith** [comment]
Great! Thanks for the tip @stooz5
